---
# file: playbook.yml

- name: Ansible Playbook for configuring brand new Raspberry Pi
  hosts: raspberries
  gather_facts: True
  roles:
    - pi
  remote_user: pi
  become: yes

- name: Setup pip
  hosts: raspberries
  become: yes
  roles:
    - pip

- name: Install docker
  hosts: raspberries
  become: yes
  roles:
    - docker
  tags: docker

- name: Install Python docker container
  hosts: raspberries
  become: yes
  roles:
    - dockerPython
  tags: python

- name: Install Telegram docker container
  hosts: raspberries
  become: yes
  roles:
    - dockerTelegram
  tags: telegram

#- name: Setup jupyter
#  hosts: jupyter
#  roles:
#    - jupyter
#  tags: jupyter
