---
# file: playbook.yml

- name: Ansible Playbook for configuring brand new Raspberry Pi
  hosts: raspberries
  gather_facts: True
  roles:
    - pi
  remote_user: pi
  become: yes

- name: Setup pip
  hosts: jupyter
  roles: 
    - pip

- name: Setup jupyter
  hosts: jupyter
  roles:
    - jupyter
