---
# file: playbook.yml

## Tested and verified 29-Mar-2020
- name: Ansible Playbook for configuring brand new Raspberry Pi
  hosts: raspberries
  gather_facts: False
  roles:
    - pi
  remote_user: pi
  become: yes
  tags: initrpi

#- name: Setup pip
#  hosts: raspberries
#  roles:
#    - pip
#  remote_user: pi
#  become: yes
#  tags: pip

## Tested and verified 09-Apr-2020
- name: Install pip via apt
  hosts: raspberries
  roles:
    - pip-via-apt
  remote_user: pi
  become: yes
  tags: pip-via-apt

- name: Install docker
  hosts: raspberries
  become: yes
  roles:
    - docker
  tags: docker

- name: Install docker-arm
  hosts: raspberries
  become: yes
  roles:
    - docker_arm
  tags: dockerarm

#- name: Install Python docker container
#  hosts: raspberries
#  become: yes
#  roles:
#    - dockerPython
#  tags: python

#- name: Install Telegram docker container
#  hosts: raspberries
#  become: yes
#  roles:
#    - dockerTelegram
#  tags: telegram

#- name: Setup jupyter
#  hosts: jupyter
#  roles:
#    - jupyter
#  tags: jupyter
