---
# files: main.yml

- name: 'Transfer init scripts'
  become: yes
  become_method: sudo
  copy: src=./ dest=/home/pi/init/ mode=0755

- name: 'Thin out Raspbian'
  become: yes
  become_method: sudo
  shell: /home/pi/init/anti-raspbian-bloat.sh

- apt: update_cache=yes
  name: 'Update apt cache'
  become: yes
  become_method: sudo

- apt: upgrade=dist
  name: 'Upgrade apt dist'
  become: yes
  become_method: sudo

#- name: 'Reboot'
#  become: yes
#  become_method: sudo
#  command: shutdown -r now "Ansible updates triggered"
#  async: 0
#  poll: 0
#  ignore_errors: true
