---
- name: Install pip3 via apt
  apt:
    name: python3-pip
    state: latest
    update_cache: yes
    cache_valid_time: 3600

- name: Install pip2 via apt
  apt:
    name: python-pip
    state: latest
    update_cache: yes
    cache_valid_time: 3600
